"""add student model

Revision ID: 17591b628cc1
Revises: 453aeedadd73
Create Date: 2020-08-25 21:10:11.987407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17591b628cc1'
down_revision = '453aeedadd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    op.drop_table('students')
    # ### end Alembic commands ###
