"""add default num of days field

Revision ID: 20abd4a1b35f
Revises: 439cbe077100
Create Date: 2020-08-27 22:39:31.111229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20abd4a1b35f'
down_revision = '439cbe077100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('default_num_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'default_num_days')
    # ### end Alembic commands ###
