"""added secodn time is_certificate_needed field

Revision ID: 453aeedadd73
Revises: d066b3606aa3
Create Date: 2020-08-25 19:42:08.590866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453aeedadd73'
down_revision = 'd066b3606aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_certificate_needed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_certificate_needed')
    # ### end Alembic commands ###
