"""change username to name

Revision ID: 9b643d5d26c4
Revises: bf39cb403847
Create Date: 2020-08-26 00:13:25.994996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b643d5d26c4'
down_revision = 'bf39cb403847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('students', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
