"""LmsTasks and Blockas

Revision ID: ad4a622aa701
Revises: 0209e5fcebf3
Create Date: 2020-08-23 01:29:52.505705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad4a622aa701'
down_revision = '0209e5fcebf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseBlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lmsTasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lms_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['courseBlocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('courses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('lmsTasks')
    op.drop_table('courseBlocks')
    # ### end Alembic commands ###
