"""delete link field

Revision ID: f3a6881426d7
Revises: 20abd4a1b35f
Create Date: 2020-08-27 22:50:48.709969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a6881426d7'
down_revision = '20abd4a1b35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('link', mysql.VARCHAR(length=140), nullable=False))
    # ### end Alembic commands ###
