"""Убрал как будто бы лишнее поле у студента

Revision ID: 15a781c32c7c
Revises: 98629d1793e4
Create Date: 2020-09-20 21:25:50.520065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a781c32c7c'
down_revision = '98629d1793e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_ibfk_2', 'students', type_='foreignkey')
    op.drop_column('students', 'telegram_state_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('telegram_state_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_ibfk_2', 'students', 'telegram_states', ['telegram_state_id'], ['id'])
    # ### end Alembic commands ###
