"""Модель телеграм переписки с ботом

Revision ID: 179c526c91e9
Revises: 133e55a5bee5
Create Date: 2020-09-06 21:27:37.020040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179c526c91e9'
down_revision = '133e55a5bee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('current_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_states')
    # ### end Alembic commands ###
