"""Создал модель чеков

Revision ID: 18a3e1b6e9c6
Revises: 54b472140155
Create Date: 2020-09-20 17:44:52.794705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a3e1b6e9c6'
down_revision = '54b472140155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['course_blocks.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checks')
    # ### end Alembic commands ###
