"""Поле ника для телеги

Revision ID: 4028ddc57d5b
Revises: 45f7d21a20af
Create Date: 2021-01-06 17:33:05.224510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4028ddc57d5b'
down_revision = '45f7d21a20af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_nickname')
    # ### end Alembic commands ###
