"""add lms email field

Revision ID: 439cbe077100
Revises: 9b643d5d26c4
Create Date: 2020-08-27 22:36:02.182537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439cbe077100'
down_revision = '9b643d5d26c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('lms_email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'students', ['lms_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'lms_email')
    # ### end Alembic commands ###
