"""Поле для отзыва о курсе

Revision ID: 448ccbb529c1
Revises: 7f6d52e2a594
Create Date: 2021-01-23 23:20:13.168267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448ccbb529c1'
down_revision = '7f6d52e2a594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('review_link', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'review_link')
    # ### end Alembic commands ###
