"""Перенес флаг отправки почты в модель юзера

Revision ID: 45f7d21a20af
Revises: 47d52a2aaab4
Create Date: 2020-12-29 18:11:14.483813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45f7d21a20af'
down_revision = '47d52a2aaab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'flag_emails_from_default_mail')
    op.add_column('users', sa.Column('flag_emails_from_default_mail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag_emails_from_default_mail')
    op.add_column('students', sa.Column('flag_emails_from_default_mail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
