"""empty message

Revision ID: 47d52a2aaab4
Revises: f26b45e0c461
Create Date: 2020-12-29 18:04:51.407417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d52a2aaab4'
down_revision = 'f26b45e0c461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('flag_emails_from_default_mail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'flag_emails_from_default_mail')
    # ### end Alembic commands ###
