"""empty message

Revision ID: 4d4bcd72a306
Revises: 15a781c32c7c
Create Date: 2020-12-27 01:47:13.383314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4bcd72a306'
down_revision = '15a781c32c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'deleted')
    # ### end Alembic commands ###
