"""В блок ссылку на материал

Revision ID: 4f5754e62acd
Revises: 18a3e1b6e9c6
Create Date: 2020-09-20 19:07:16.290952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5754e62acd'
down_revision = '18a3e1b6e9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_blocks', sa.Column('link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_blocks', 'link')
    # ### end Alembic commands ###
