"""Сделал поле статус для статуса студента

Revision ID: 54b472140155
Revises: cd84249b09fe
Create Date: 2020-09-20 01:36:52.628347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54b472140155'
down_revision = 'cd84249b09fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('status', sa.String(length=100), nullable=False))
    op.drop_column('students', 'finished')
    op.drop_column('students', 'dropped')
    op.drop_column('students', 'freezed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('freezed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('dropped', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('finished', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('students', 'status')
    # ### end Alembic commands ###
