"""Добавил поле finished студенту

Revision ID: 5b7da3c5cdd4
Revises: df0d203da526
Create Date: 2020-09-18 18:52:40.039428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7da3c5cdd4'
down_revision = 'df0d203da526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'finished')
    # ### end Alembic commands ###
