"""Добавил поле help для курса

Revision ID: 5ba56021ae94
Revises: f224b2b02005
Create Date: 2021-02-03 01:26:53.753914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ba56021ae94'
down_revision = 'f224b2b02005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('help', sa.Text(), nullable=False))
    op.alter_column('homeworks', 'number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('courses', 'help')
    # ### end Alembic commands ###
