"""Сделал поле telegram_id уникальным

Revision ID: 638a27189f75
Revises: 179c526c91e9
Create Date: 2020-09-06 21:35:28.290201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638a27189f75'
down_revision = '179c526c91e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'telegram_states', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_states', type_='unique')
    # ### end Alembic commands ###
