"""Поле для ссылки на сертификат

Revision ID: 7f6d52e2a594
Revises: 4028ddc57d5b
Create Date: 2021-01-17 16:47:35.551727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6d52e2a594'
down_revision = '4028ddc57d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('cert_link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'cert_link')
    # ### end Alembic commands ###
