"""Поле доходят ли сообщения из телеги тренеру

Revision ID: 916625dbd4a8
Revises: 5ba56021ae94
Create Date: 2021-02-03 22:40:33.993025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916625dbd4a8'
down_revision = '5ba56021ae94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag_is_messages_from_bot_is_delivered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag_is_messages_from_bot_is_delivered')
    # ### end Alembic commands ###
