"""deleted для блока

Revision ID: 98629d1793e4
Revises: 4f5754e62acd
Create Date: 2020-09-20 19:16:24.483159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98629d1793e4'
down_revision = '4f5754e62acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_blocks', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_blocks', 'deleted')
    # ### end Alembic commands ###
