"""add student fields

Revision ID: a0a38d9dc506
Revises: 17591b628cc1
Create Date: 2020-08-25 21:31:42.482059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a38d9dc506'
down_revision = '17591b628cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('freezed', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('lms_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('number_of_days', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('registration_code_hash', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('username', sa.String(length=100), nullable=False))
    # op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'username')
    op.drop_column('students', 'telegram_id')
    op.drop_column('students', 'registration_code_hash')
    op.drop_column('students', 'number_of_days')
    op.drop_column('students', 'lms_id')
    op.drop_column('students', 'freezed')
    op.drop_column('students', 'email')
    op.drop_column('students', 'deleted')
    # ### end Alembic commands ###
