"""Изменил название поля

Revision ID: ad39d7ea81a7
Revises: f3a6881426d7
Create Date: 2020-09-04 23:33:54.826545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad39d7ea81a7'
down_revision = 'f3a6881426d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('registration_code', sa.String(length=100), nullable=False))
    op.drop_column('students', 'registration_code_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('registration_code_hash', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('students', 'registration_code')
    # ### end Alembic commands ###
