"""course trainer fields

Revision ID: c895cccce7b7
Revises: 7bbe120919f9
Create Date: 2020-08-19 01:47:07.688181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c895cccce7b7'
down_revision = '7bbe120919f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('trainer_lms_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('trainer_telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'trainer_telegram_id')
    op.drop_column('courses', 'trainer_lms_id')
    # ### end Alembic commands ###
