"""Поле студента бросил курс

Revision ID: cd84249b09fe
Revises: 5b7da3c5cdd4
Create Date: 2020-09-20 01:07:45.321991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd84249b09fe'
down_revision = '5b7da3c5cdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dropped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'dropped')
    # ### end Alembic commands ###
