"""Добавил поля дат

Revision ID: d1c4189c67f2
Revises: e38ce1128a87
Create Date: 2020-12-27 21:52:06.481490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c4189c67f2'
down_revision = 'e38ce1128a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('checks', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'updated_on')
    op.drop_column('students', 'created_on')
    op.drop_column('courses', 'updated_on')
    op.drop_column('courses', 'created_on')
    op.drop_column('checks', 'updated_on')
    op.drop_column('checks', 'created_on')
    # ### end Alembic commands ###
