"""Темповое поле для курса

Revision ID: d871b178d1e9
Revises: 6bd0ae1c00a2
Create Date: 2020-09-12 21:48:16.620460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd871b178d1e9'
down_revision = '6bd0ae1c00a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_states', sa.Column('temp_course_register_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_states', 'courses', ['temp_course_register_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_states', type_='foreignkey')
    op.drop_column('telegram_states', 'temp_course_register_id')
    # ### end Alembic commands ###
