"""Поле tmp_authcode не является необходимым

Revision ID: df0d203da526
Revises: 79a239bf0c52
Create Date: 2020-09-13 16:45:16.616203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df0d203da526'
down_revision = '79a239bf0c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_states', 'temp_authcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_states', sa.Column('temp_authcode', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
