"""Добавил в чек возможность оплаты не за блок

Revision ID: e38ce1128a87
Revises: 4d4bcd72a306
Create Date: 2020-12-27 21:32:39.885727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38ce1128a87'
down_revision = '4d4bcd72a306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('another', sa.String(length=50), nullable=True))
    op.alter_column('checks', 'block_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checks', 'block_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('checks', 'another')
    # ### end Alembic commands ###
