"""Add num block field to course

Revision ID: ea54b96ff65f
Revises: 0937a8bfdd23
Create Date: 2020-08-23 17:51:10.552772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea54b96ff65f'
down_revision = '0937a8bfdd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('num_of_blocks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'num_of_blocks')
    # ### end Alembic commands ###
