"""Добавил дз вспомогательное поле number

Revision ID: f224b2b02005
Revises: 4c4b76fc7d44
Create Date: 2021-02-02 20:44:43.626090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f224b2b02005'
down_revision = '4c4b76fc7d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'number')
    # ### end Alembic commands ###
