"""Вношу в модель чеков поле суммы

Revision ID: f26b45e0c461
Revises: d1c4189c67f2
Create Date: 2020-12-27 21:55:33.425649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b45e0c461'
down_revision = 'd1c4189c67f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'amount')
    # ### end Alembic commands ###
