"""not null field

Revision ID: fe8466074bb8
Revises: 459756de569f
Create Date: 2020-08-26 00:01:15.832603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe8466074bb8'
down_revision = '459756de569f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'link',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'link',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###
